name: ğŸ“¦ CI/CD
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  CI: true

jobs:
  test:
    runs-on: ubuntu-latest
    name: ğŸ§ª test ttrpg.tech
    steps:
      - name: ğŸ“¦ Checkout Repository
        uses: actions/checkout@v5
        with:
          submodules: true

      - name: ğŸ”¨ Set npm
        uses: actions/setup-node@v5
        with:
          node-version-file: package.json
          cache-dependency-path: package-lock.json

      - name: âš’ï¸ Setup project
        run: npm ci

      - name: ğŸ› ï¸ Build
        run: npm run build
        env:
          NODE_ENV: production

      - name: ğŸ­ Playwright
        run: npx playwright install
        env:
          NODE_ENV: production

      - name: ğŸ“‹ Test
        run: npm run test
        env:
          NODE_ENV: production
